AllCops:
  TargetRubyVersion: 3.2.2

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 35

Metrics/BlockLength:
  Max: 90

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Metrics/AbcSize:
  Max: 30
