require:
  - rubocop-slim
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'db'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'bin/**/*'

Style/StringLiterals:
#  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
#  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Rails/ReversibleMigration:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form.rb'

Metrics/AbcSize:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

